name: Docker Tailscale Container B&P

on:
  workflow_dispatch:

env:
  TS_TAG: ${{ secrets.TAILSCALE_TAG }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build Information
        run: echo "Building new tailscale-sr container from Tailscale/Tailscale:${{ env.TS_TAG }}"
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          build-args: |
            TAILSCALE_TAG=$TS_TAG
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tailscale-sr:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tailscale-sr:${{ env.TS_TAG }}